package MajorProject1com.example.Student_LbraryManagmentSystem.Services;

import MajorProject1com.example.Student_LbraryManagmentSystem.Enums.CardStatus;
import MajorProject1com.example.Student_LbraryManagmentSystem.Models.Card;
import MajorProject1com.example.Student_LbraryManagmentSystem.Models.Student;
import MajorProject1com.example.Student_LbraryManagmentSystem.Repository.CardRepository;
import MajorProject1com.example.Student_LbraryManagmentSystem.Repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;
    public String createStudent(Student student){

        //card should be autogenerated when CreateStudent function is called
        Card card = new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student);

        //lets go to the student
        student.setCard(card);

        studentRepository.save(student);
        return "user and card added";
    }
}
